import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { HomepageCard } from 'components/homepage-card';

const Home: NextPage = () => {
  return (
    <div className="px-8 py-0">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-1 flex-col items-center justify-center py-16 px-0">
        <h1 className="m-0 text-center text-6xl leading-tight">
          Welcome to{' '}
          <a
            href="https://nextjs.org"
            className="text-blue-600 no-underline hover:underline focus:underline active:underline"
          >
            Next.js!
          </a>
        </h1>

        <p className="my-16 mx-0 text-center text-2xl leading-normal">
          Get started by editing{' '}
          <code className="rounded bg-zinc-50 p-3 font-mono text-lg">
            pages/index.tsx
          </code>
        </p>

        <div className="flex w-full max-w-[800px] flex-col flex-wrap items-center justify-center sm:w-auto sm:flex-row">
          <HomepageCard
            href="https://nextjs.org/docs"
            title="Documentation"
            description="Find in-depth information about Next.js features and API."
          />

          <HomepageCard
            href="https://nextjs.org/learn"
            title="Learn"
            description="Learn about Next.js in an interactive course with quizzes!"
          />

          <HomepageCard
            href="https://github.com/vercel/next.js/tree/canary/examples"
            title="Examples"
            description="Discover and deploy boilerplate example Next.js projects."
          />

          <HomepageCard
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            title="Deploy"
            description="Instantly deploy your Next.js site to a public URL with Vercel."
          />
        </div>
      </main>

      <footer className="flex flex-1 items-center justify-center border-t border-slate-200 py-8 px-0">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
          className="flex flex-grow items-center justify-center"
        >
          Powered by{' '}
          <span className="ml-2 h-4">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
