name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run linters
        run: yarn lint

  format-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Check formatting
        run: yarn format:check

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run codegen
        run: yarn codegen
      - name: Run unit tests
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run codegen
        run: yarn codegen
      - name: Run E2E tests
        run: yarn e2e:headless

  build:
    runs-on: ubuntu-latest
    needs:
      - lint
      - format-check
      - unit-tests
      - e2e-tests
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build project
        run: yarn build
